package hnct.lib.access.api

/**
 * AccessRequest is used to identify the party who is
 * accessing the resource. This trait only define the most basic
 * information needed for identification which is username and
 * the access token. Access token can be understood as a key for the username,
 * e.g. a password, or a string generated by server and attached to the username.
 * 
 * It is the responsibility of the party who is accessing the resource to provide
 * the correct access request, in order for the access request to pass the access manager
 * login check.
 */
trait AccessRequest {
	
	protected var _username : String
	protected var _token : String
	
	// getters and setters
	
	def username = _username
	def username_=(name : String) = {_username = name}
	
	def token = _token
	def token_=(t : String) = {_token = t}
	
}